/**
 * Full state list (spec section 54). The state machine must be
 * recoverable after a server restart — this is guaranteed simply by
 * persisting `state` on the Session document rather than in memory.
 */
const STATES = {
  LANGUAGE_SELECTION: 'LANGUAGE_SELECTION',
  MAIN_MENU: 'MAIN_MENU',

  BOOKING_TRIP_TYPE: 'BOOKING_TRIP_TYPE',
  BOOKING_PICKUP: 'BOOKING_PICKUP',
  BOOKING_DROP: 'BOOKING_DROP',
  BOOKING_DATE: 'BOOKING_DATE',
  BOOKING_TIME: 'BOOKING_TIME',
  BOOKING_RETURN_DATE: 'BOOKING_RETURN_DATE',
  BOOKING_RETURN_TIME: 'BOOKING_RETURN_TIME',
  BOOKING_RENTAL_HOURS: 'BOOKING_RENTAL_HOURS',
  BOOKING_PASSENGERS: 'BOOKING_PASSENGERS',
  BOOKING_VEHICLE_SELECTION: 'BOOKING_VEHICLE_SELECTION',
  BOOKING_FARE_CONFIRMATION: 'BOOKING_FARE_CONFIRMATION',
  BOOKING_CUSTOMER_NAME: 'BOOKING_CUSTOMER_NAME',
  BOOKING_REVIEW: 'BOOKING_REVIEW',
  BOOKING_CREATED: 'BOOKING_CREATED',

  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_VERIFICATION: 'PAYMENT_VERIFICATION',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',

  MY_BOOKINGS: 'MY_BOOKINGS',
  BOOKING_DETAILS: 'BOOKING_DETAILS',

  CANCELLATION_REASON: 'CANCELLATION_REASON',
  CANCELLATION_CONFIRMATION: 'CANCELLATION_CONFIRMATION',

  SUPPORT_CATEGORY: 'SUPPORT_CATEGORY',
  SUPPORT_MESSAGE: 'SUPPORT_MESSAGE',

  HUMAN_HANDOFF: 'HUMAN_HANDOFF',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
};

module.exports = { STATES };
